//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumTouchkit.Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-30")]
        public int MIN_DECIBEL {
            get {
                return ((int)(this["MIN_DECIBEL"]));
            }
            set {
                this["MIN_DECIBEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CHANNELS {
            get {
                return ((int)(this["CHANNELS"]));
            }
            set {
                this["CHANNELS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16000")]
        public int SAMPLE_RATE {
            get {
                return ((int)(this["SAMPLE_RATE"]));
            }
            set {
                this["SAMPLE_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCRUM")]
        public string CLIENT_NAME {
            get {
                return ((string)(this["CLIENT_NAME"]));
            }
            set {
                this["CLIENT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3001")]
        public int UDP_PORT {
            get {
                return ((int)(this["UDP_PORT"]));
            }
            set {
                this["UDP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4371")]
        public int STD_TCP_PORT {
            get {
                return ((int)(this["STD_TCP_PORT"]));
            }
            set {
                this["STD_TCP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RECORD_DEVICE {
            get {
                return ((int)(this["RECORD_DEVICE"]));
            }
            set {
                this["RECORD_DEVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLAYBACK_DEVICE {
            get {
                return ((int)(this["PLAYBACK_DEVICE"]));
            }
            set {
                this["PLAYBACK_DEVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3333")]
        public int TUIO_PORT {
            get {
                return ((int)(this["TUIO_PORT"]));
            }
            set {
                this["TUIO_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TOUCH_FEEDBACK {
            get {
                return ((bool)(this["TOUCH_FEEDBACK"]));
            }
            set {
                this["TOUCH_FEEDBACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pbf")]
        public string PRODUCT_BACKLOG_EXT {
            get {
                return ((string)(this["PRODUCT_BACKLOG_EXT"]));
            }
            set {
                this["PRODUCT_BACKLOG_EXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".sbf")]
        public string SPRINT_BACKLOG_EXT {
            get {
                return ((string)(this["SPRINT_BACKLOG_EXT"]));
            }
            set {
                this["SPRINT_BACKLOG_EXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COMPRESS {
            get {
                return ((bool)(this["COMPRESS"]));
            }
            set {
                this["COMPRESS"] = value;
            }
        }
    }
}
